apiVersion: apps/v1
kind: Deployment
metadata:
  name: options
  namespace: ryan-nix-dev
spec:
  selector:
    matchLabels:
      app: options
  template:
    metadata:
      labels:
        app: options
    spec:
      containers:
      - name: options
        image: quay.io/ryan_nix/options_demo
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: options-hpa
  namespace: ryan-nix-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: options
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      stabilizationWindowSeconds: 300